config/routes.rb
Lbl::Application.routes.draw do

  get "index", to: "main#index"
  root "main#index"

  namespace :admin do
    root "admin#index"
    resources :pictures, :people, :projects
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  get "/:id", to: "main#project_page"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :project
  has_attached_file :bitmap, :styles => {
    :large => ["1280", :jpg],
    :medium => ["640", :jpg],
    :small => ["320", :jpg],
    :thumb => ["160x160#", :jpg]
    }
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < Admin::AdminController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.order("id DESC").all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to [:admin, @picture], notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to [:admin, @picture], notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to admin_pictures_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_picture
    @picture = Picture.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def picture_params
    params.require(:picture).permit(:caption, :credit, :weight, :project_id, :bitmap)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/admin/pictures/_form.html.erb
<%= form_for [:admin, @picture] do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.text_field :credit %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.select :project_id, Project.all.collect {|p| [p.title, p.id] } %>
  </div>
  <div class="field">
     <%= f.file_field :bitmap %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pictures/_info.html.erb
<h4><%= picture.caption %></h4>
<p>
	<%= picture.credit %>
</p>
<p>
	<label>Weight:</label> <%= picture.weight %><br/>
	<label>Project:</label> <%= picture.project.title %>
</p>
<%= image_tag picture.bitmap.url %>

app/views/admin/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_picture_path(@picture) %> |
<%= link_to 'Back', admin_pictures_path %>

app/views/admin/pictures/index.html.erb
<h1>Pictures List</h1>

<br>
<%= link_to 'New Picture', new_admin_picture_path, class: "btn btn-large" %>
<br>

<div class="list">
	<% @pictures.each do |picture| %>
	<article>
		<%= render partial: "info", locals: { picture: picture } %>
		<div class="actions">
      <%= link_to 'Show', admin_picture_path(picture), class: "btn" %>
      <%= link_to 'Edit', edit_admin_picture_path(picture), class: "btn" %>
      <%= link_to 'Destroy', admin_picture_path(picture), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
    </div>
	</article>
	<% end %>
</div>

app/views/admin/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pictures_path %>

app/views/admin/pictures/show.html.erb
<article>
  <%= render partial: "info", locals: { picture:@picture } %>
</article>
<%= link_to 'Edit', edit_admin_picture_path(@picture) %> |
<%= link_to 'Back', admin_pictures_path %>