config/routes.rb
Lbl::Application.routes.draw do

  get "index", to: "main#index"
  root "main#index"

  namespace :admin do
    root "admin#index"
    resources :pictures, :people, :projects
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  get "/:id", to: "main#project_page"

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates_presence_of :title

  before_create :create_slug

  has_attached_file :bitmap, :styles => {
    :small => ["350", :jpg],
    :square => ["350x350#", :jpg]
  }

  def to_param
    slug
  end

  def create_slug
    self.slug = self.title.parameterize
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @projects = Project.order("id DESC").all
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
    @project = Project.find_by_slug(params[:id])
  end

  # GET /admin/projects/new
  def new
    @project = Project.new
  end

  # GET /admin/projects/1/edit
  def edit
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find_by_slug(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:title, :summary, :description, :client, :credit, :role, :website_url, :date, :awards, :bitmap, :slug)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "title" %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, class: "summary" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "description" %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client, class: "client" %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.text_field :credit, class: "credit" %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role, class: "role" %>
  </div>
  <div class="field">
    <%= f.label :website_url %><br>
    <%= f.text_field :website_url, class: "url" %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :start_year => 2001, class: "date" %>
  </div>
  <div class="field">
    <%= f.label :awards %><br>
    <%= f.text_area :awards, class: "awards" %>
  </div>
  <div class="field">
    <%= f.label :bitmap %><br>
    <%= f.file_field :bitmap %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, class: "slug" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/_info.html.erb
<h2><%= project.title %></h2>
<h4><%= raw project.summary %></h4>
<p><%= raw project.description %></p>
<h5><strong>Client:</strong> <%= project.client %> </h5>
<h5><strong>Credit</strong> <%= project.credit %> </h5>
<h5><strong>Role:</strong> <%= project.role %> </h5>
<h5><strong>Website:</strong> <%= link_to project.website_url %> </h5>
<h5><strong>Date:</strong> <%= project.date %> </h5>
<h5><strong>Awards</strong> <%= project.awards %> </h5>
<h5><strong>Slug:</strong> <%= project.slug %> </h5>
<p><%= image_tag project.bitmap.url %></p>

app/views/admin/projects/edit.html.erb
<h2>Edit project</h2>

<%= render 'form' %>

<%= link_to 'Show', admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<h2>Project List</h2>

<div class="list">
	<% @projects.each do |project| %>
	<article>
		<%= render partial: "info", locals: { project: project } %>
		<div class="actions">
			<%= link_to 'Show', admin_project_path(project), class: "btn" %>
			<%= link_to 'Edit', edit_admin_project_path(project), class: "btn" %>
			<%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
		</div>
	</article>
	<% end %>
</div>

<br>

<%= link_to 'New Project', new_admin_project_path, class: "btn btn-primary" %>

app/views/admin/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<article>
  <%= render partial: "info", locals: { project: @project } %>
  <%= link_to 'Edit', edit_admin_project_path(@project), class: "btn" %>
  <%= link_to 'Back', admin_projects_path, class: "btn" %>
</article>